source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'crichton', git: 'git@github.com:mdsol-share/crichton.git', branch: 'develop', require: false #FIXME
gem 'representors', git: 'git@github.com:mdsol-share/representors.git', branch: '0-0-stable' #FIXME
gem 'dice_bag', '~> 0.8'
gem 'activeuuid', '~> 0.5'
gem 'pry'

